name: Lesson 9

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Lesson9/Lesson9.sln
    - name: Build
      run: dotnet build Lesson9/Lesson9.sln
    - name: Test
      run: dotnet test Lesson9/Lesson9.sln
